version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: nombre_de_tu_base_de_datos
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_contraseña
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=nombre_de_tu_base_de_datos
      - DATABASE_USER=tu_usuario
      - DATABASE_PASSWORD=tu_contraseña
    depends_on:
      - db
